frontend:
  image: matefreitasneto/frontend:1.0.3
  replicas: 1
  port: 8080

backend:
  image: matefreitasneto/backend:1.0.0
  replicas: 2
  port: 5000

postgres:
  image: postgres:latest
  port: 5432
  user: postgres
  password: secretpass
  db: postgres
  storage: 1Gi

hpa:
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 80

env:
  FLASK_APP: "run.py"
  FLASK_DB_TYPE: "postgres"
  FLASK_DB_USER: "postgres"
  FLASK_DB_NAME: "postgres"
  FLASK_DB_PASSWORD: "secretpass"
  FLASK_DB_HOST: "postgres"
  FLASK_DB_PORT: "5432"