apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
  labels:
    type: local  
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data/postres
